CREATE TABLE public.KATEGORI
(
    ID numeric(19) NOT NULL,
    KIRILIM numeric(2) NOT NULL,
    ADI character(50) NOT NULL,
    UST_KATEGORI_ID numeric(19) REFERENCES KATEGORI(ID) MATCH SIMPLE,
    PRIMARY KEY (ID)
);


CREATE TABLE PUBLIC.URUN 
(
    ID NUMERIC(19) NOT NULL,
    ADI CHARACTER(50) NOT NULL,
    FIYAT NUMERIC(19,2) NOT NULL,
    KAYIT_TARIHI TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_DATE,
    KATEGORI_ID NUMERIC(19) NOT NULL REFERENCES KATEGORI(ID) MATCH SIMPLE,
    PRIMARY KEY (ID)
)
;


CREATE TABLE PUBLIC.KULLANICI 
(
    ID NUMERIC(19) NOT NULL,
    ADI CHARACTER(50) NOT NULL,
    SOYADI CHARACTER(50) NOT NULL,
    EMAIL CHARACTER(50) NOT NULL,
    TELEFON CHARACTER(15) NOT NULL,
    PRIMARY KEY (ID)
)
;


CREATE TABLE PUBLIC.URUNYORUM 
(
    ID NUMERIC(19) NOT NULL,
    YORUM CHARACTER(500) NOT NULL,
    YORUMTARIHI TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_DATE,
    URUN_ID NUMERIC(19) NOT NULL REFERENCES URUN(ID) MATCH SIMPLE,
    KULLANICI_ID NUMERIC(19) NOT NULL REFERENCES KULLANICI(ID) MATCH SIMPLE,
    PRIMARY KEY (ID)
)
;